### ISSUE TITLE
I was playing without problems for months but since a couple of days everytime that I tried to get in my singleplayer world I get this meesage in the log ''java.lang.IllegalStateException: No server set.'' I don't know what to do. versions is 

### ISSUE THREAD

**Issue by jhernandez166** [AbdulMuqsit/Starpack-Aleph#133]
**Describe the bug**

**Modpack Version**
- [ ] Aleph
- [x] Titan

**To Reproduce**

**Expected behavior**
(Do not need to mention it, if it is super obvious)

**Screenshots**

**Logs**
Provide latest and crash logs if applicable.

**Comment by jhernandez166** [comment]
Listeners:
		0: HIGH
		1: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/fml/event/server/FMLServerStoppedEvent;)V
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@205081e
		4: ASM: class dev.ftb.mods.ftbessentials.FTBEEventHandler serverStopped(Lnet/minecraftforge/fml/event/server/FMLServerStoppedEvent;)V
		5: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@b78124e
		6: ASM: class com.mrcrayfish.goblintraders.world.spawner.SpawnHandler onServerStart(Lnet/minecraftforge/fml/event/server/FMLServerStoppedEvent;)V
		7: ASM: net.roguelogix.phosphophyllite.Phosphophyllite@243c27bf onServerStopped(Lnet/minecraftforge/fml/event/server/FMLServerStoppedEvent;)V
		8: ASM: me.ichun.mods.hats.common.core.EventHandlerServer@459f20c4 onServerStopped(Lnet/minecraftforge/fml/event/server/FMLServerStoppedEvent;)V
		9: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@40b094f0
		10: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@304f8a36
		11: ASM: class sonar.fluxnetworks.register.CommonEventHandler onServerStopped(Lnet/minecraftforge/fml/event/server/FMLServerStoppedEvent;)V
		12: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@1a2021d9
		13: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@5101bab1
		14: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@15d2b375
		15: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@590085c3
		16: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@42b549d3
		17: ASM: class com.terraforged.mod.server.ServerEvents serverStop(Lnet/minecraftforge/fml/event/server/FMLServerStoppedEvent;)V
		18: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@1e3db706
		19: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@1e74f6af
		20: ASM: me.ichun.mods.morph.common.core.EventHandlerServer@55ec53eb onServerStopped(Lnet/minecraftforge/fml/event/server/FMLServerStoppedEvent;)V
		21: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@4307563f
		22: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@2b94645d
		23: ASM: class dan200.computercraft.shared.CommonHooks onServerStopped(Lnet/minecraftforge/fml/event/server/FMLServerStoppedEvent;)V
		24: ASM: invtweaks.InvTweaksMod@16272b5a onServerStopped(Lnet/minecraftforge/fml/event/server/FMLServerStoppedEvent;)V
		25: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@586273ae
		26: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@619a2783
		27: ASM: com.infinityraider.infinitylib.InfinityLib@54b41057 onServerStoppedEvent(Lnet/minecraftforge/fml/event/server/FMLServerStoppedEvent;)V
		28: ASM: com.infinityraider.agricraft.AgriCraft@228206bb onServerStoppedEvent(Lnet/minecraftforge/fml/event/server/FMLServerStoppedEvent;)V
		29: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@18d52321
		30: ASM: top.theillusivec4.polymorph.common.CommonEventsListener@54e9c719 serverStopped(Lnet/minecraftforge/fml/event/server/FMLServerStoppedEvent;)V
		31: net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654@106b1aea
java.lang.IllegalStateException: No server set.
	at appeng.core.worlddata.WorldData.instance(WorldData.java:92)
	at appeng.core.AppEng.serverStopped(AppEng.java:218)
	at appeng.core.AppEng$$Lambda$40955/1457096019.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2962/182367654.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus$$Lambda$3807/358952574.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:124)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$76724/1044602855.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

[13:06:54] [Server thread/ERROR]: java.lang.IllegalStateException: No server set.
